
server:
  port: 9999
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employeedb
    username: root
    password: root
    
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
